# Generated by Django 3.0 on 2019-12-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
